backend:
  name: git-gateway
  branch: master
  squash_merges: true

#publish_mode: editorial_workflow

media_library:
  name: cloudinary
  config:
    default_transformations:
    #  -   - fetch_format: auto
    #        width: 160
    #        quality: auto
    #        crop: scale
    
    cloud_name: whanganuihigh
    api_key: 514169267776294

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
  
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Image Filename"
        name: "image"
        widget: "image"
        required: false
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "about_whs"
    label: "About WHS"
    label_singular: "About WHS Entry"
    folder: "source/_about"
    create: true
    slug: "{{slug}}"

    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Image Filename"
        name: "image"
        widget: "image"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "for-parents"
    label: "For Parents"
    label_singular: "For Parents Entry"
    folder: "source/_for_parents"
    create: true
    slug: "{{slug}}"
    
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Image Filename"
        name: "image"
        widget: "image"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "curriculum"
    label: "Curriculum"
    label_singular: "Curriculum Entry"
    folder: "source/_curriculum"
    create: true
    slug: "{{slug}}"
    
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Image Filename"
        name: "image"
        widget: "image"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "news"
    label: "News"
    label_singular: "News Article"
    folder: "source/_news"
    create: true
    slug: "{{slug}}"
    
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Image Filename"
        name: "image"
        widget: "image"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "international"
    label: "International"
    label_singular: "International Entry"
    folder: "source/_international"
    create: true
    slug: "{{slug}}"
    
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Image Filename"
        name: "image"
        widget: "image"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "staff"
    label: "Staff"
    label_singular: "Staff Member"
    folder: "source/_staff"
    create: true
    slug: "{{slug}}"
    
    fields:
      
      - {label: "Title", name: "title", widget: "string", default: "Joe"}
      - {label: "First Name", name: "firstName", widget: "string", default: "Joe"}
      - {label: "Last Name", name: "lastName", widget: "string", default: "Bloggs"}
      - label: "Departments"
        label_singular: "Department"
        name: "departments"
        widget: "list"
      - label: "Image Filename"
        name: "image"
        widget: "image"
        required: false

  - name: "policies"
    label: "Policies"
    label_singular: "Policy"
    folder: "source/_policies"
    create: true
    slug: "{{slug}}"
    
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - name: "policyAreas"
        label: "Policy Areas"
        label_singular: "Policy Area"
        widget: "list"
        fields:
          - label: "Policy Area Name"
            name: "policyArea"
            widget: "string"
          - label: "Policies"
            name: policies
            widget: list
            fields:
              - name: "policy"
                label: "Policy"
                widget: "string"
              - name: document
                label: "Document"
                widget: file
                allow_multiple: false

