backend:
  name: git-gateway
  branch: master
  squash_merges: true

publish_mode: editorial_workflow

media_library:
  name: cloudinary
  cloud_name: whanganuihigh
  api_key: 514169267776294
  output_filename_only: false
  config:
    default_transformations:
      -   - fetch_format: auto
            width: 160
            quality: auto
            crop: scale

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    media_library:
      name: cloudinary
      cloud_name: whanganuihigh
      api_key: 514169267776294
  
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Image Filename"
        name: "image"
        widget: "image"
        required: false
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
